-- SmartTeachingPlatform Database Schema (PostgreSQL)
-- Based on teaching_ops_pg.sql — 27 tables
-- All tables use IF NOT EXISTS for safe re-run

-- ============================================================
-- Level 0 — no foreign keys
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    real_name     varchar(100),
    email         varchar(150),
    phone         varchar(30),
    user_no       varchar(100),
    avatar_url    varchar(500),
    status        varchar(30)  NOT NULL DEFAULT 'active',
    created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT users_chk_1 CHECK (status IN ('active','disabled'))
);
CREATE INDEX IF NOT EXISTS idx_users_email    ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_user_no ON users (user_no) WHERE user_no IS NOT NULL;

CREATE TABLE IF NOT EXISTS roles (
    id        serial       PRIMARY KEY,
    role_code varchar(50)  NOT NULL,
    role_name varchar(100) NOT NULL,
    CONSTRAINT uk_roles_code UNIQUE (role_code)
);

-- ============================================================
-- Level 1 — depend on users / roles only
-- ============================================================

CREATE TABLE IF NOT EXISTS courses (
    id          bigserial    PRIMARY KEY,
    course_name varchar(200) NOT NULL,
    course_code varchar(100),
    semester    varchar(100),
    teacher_id  bigint       NOT NULL,
    description text,
    invite_code varchar(50),
    status      varchar(30)  NOT NULL DEFAULT 'draft',
    created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_courses_code   UNIQUE (course_code),
    CONSTRAINT uk_courses_invite UNIQUE (invite_code),
    CONSTRAINT courses_chk_1 CHECK (status IN ('draft','active','archived'))
);
CREATE INDEX IF NOT EXISTS idx_courses_teacher_id ON courses (teacher_id);
CREATE INDEX IF NOT EXISTS idx_courses_semester   ON courses (semester);

CREATE TABLE IF NOT EXISTS user_roles (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT uk_user_roles_user_role UNIQUE (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles (role_id);

-- ============================================================
-- Level 2 — depend on courses / users
-- ============================================================

CREATE TABLE IF NOT EXISTS knowledge_nodes (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   bigint        NOT NULL,
    parent_id   bigint,
    node_name   varchar(200)  NOT NULL,
    node_desc   text,
    difficulty  int           NOT NULL DEFAULT 1,
    sort_order  int           NOT NULL DEFAULT 0,
    x_position  decimal(10,2),
    y_position  decimal(10,2),
    status      varchar(30)   NOT NULL DEFAULT 'active',
    created_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT knowledge_nodes_chk_1 CHECK (difficulty BETWEEN 1 AND 5),
    CONSTRAINT knowledge_nodes_chk_2 CHECK (status IN ('active','hidden'))
);
CREATE INDEX IF NOT EXISTS idx_knowledge_nodes_course_id ON knowledge_nodes (course_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_nodes_parent_id ON knowledge_nodes (parent_id);

CREATE TABLE IF NOT EXISTS resources (
    id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     bigint        NOT NULL,
    uploader_id   bigint        NOT NULL,
    resource_name varchar(200)  NOT NULL,
    resource_type varchar(30)   NOT NULL,
    file_url      varchar(1000) NOT NULL,
    file_size     bigint,
    duration      int,
    description   text,
    created_at    timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT resources_chk_1 CHECK (resource_type IN ('pdf','ppt','video','link','document','image','other')),
    CONSTRAINT resources_chk_2 CHECK ((file_size IS NULL) OR (file_size >= 0)),
    CONSTRAINT resources_chk_3 CHECK ((duration  IS NULL) OR (duration >= 0))
);
CREATE INDEX IF NOT EXISTS idx_resources_course_id   ON resources (course_id);
CREATE INDEX IF NOT EXISTS idx_resources_uploader_id ON resources (uploader_id);

CREATE TABLE IF NOT EXISTS quizzes (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   bigint        NOT NULL,
    title       varchar(200)  NOT NULL,
    description text,
    start_time  timestamp,
    end_time    timestamp,
    total_score decimal(8,2)  NOT NULL DEFAULT 0.00,
    status      varchar(30)   NOT NULL DEFAULT 'draft',
    created_by  bigint        NOT NULL,
    created_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT quizzes_chk_1 CHECK (status IN ('draft','published','closed')),
    CONSTRAINT quizzes_chk_2 CHECK ((end_time IS NULL) OR (start_time IS NULL) OR (end_time >= start_time))
);
CREATE INDEX IF NOT EXISTS idx_quizzes_course     ON quizzes (course_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_created_by ON quizzes (created_by);

CREATE TABLE IF NOT EXISTS learning_plans (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id    bigint       NOT NULL,
    student_id   bigint       NOT NULL,
    title        varchar(200) NOT NULL,
    plan_content text,
    generated_by varchar(30)  NOT NULL DEFAULT 'agent',
    status       varchar(30)  NOT NULL DEFAULT 'active',
    created_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT learning_plans_chk_1 CHECK (generated_by IN ('agent','teacher','student')),
    CONSTRAINT learning_plans_chk_2 CHECK (status       IN ('active','completed','archived'))
);
CREATE INDEX IF NOT EXISTS idx_learning_plans_course  ON learning_plans (course_id);
CREATE INDEX IF NOT EXISTS idx_learning_plans_student ON learning_plans (student_id);

CREATE TABLE IF NOT EXISTS questions (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         bigint      NOT NULL,
    knowledge_node_id bigint,
    question_type     varchar(30) NOT NULL,
    stem              text        NOT NULL,
    answer            text,
    analysis          text,
    difficulty        int         NOT NULL DEFAULT 1,
    created_by        bigint      NOT NULL,
    created_at        timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT questions_chk_1 CHECK (question_type IN ('single','multiple','judge','blank','short_answer')),
    CONSTRAINT questions_chk_2 CHECK (difficulty BETWEEN 1 AND 5)
);
CREATE INDEX IF NOT EXISTS idx_questions_created_by        ON questions (created_by);
CREATE INDEX IF NOT EXISTS idx_questions_course_id         ON questions (course_id);
CREATE INDEX IF NOT EXISTS idx_questions_knowledge_node_id ON questions (knowledge_node_id);

CREATE TABLE IF NOT EXISTS agent_events (
    id           bigserial    PRIMARY KEY,
    event_type   varchar(50)  NOT NULL,
    course_id    bigint,
    user_id      bigint,
    payload      jsonb        NOT NULL,
    status       varchar(30)  NOT NULL DEFAULT 'new',
    created_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamp,
    CONSTRAINT agent_events_chk_1 CHECK (event_type IN ('quiz_submitted','mastery_updated','risk_detected','plan_updated')),
    CONSTRAINT agent_events_chk_2 CHECK (status     IN ('new','processed','failed'))
);
CREATE INDEX IF NOT EXISTS idx_agent_events_course              ON agent_events (course_id);
CREATE INDEX IF NOT EXISTS idx_agent_events_user                ON agent_events (user_id);
CREATE INDEX IF NOT EXISTS idx_agent_events_type_status_created ON agent_events (event_type, status, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_conversations (
    id         bigserial    PRIMARY KEY,
    user_id    bigint       NOT NULL,
    course_id  bigint,
    role       varchar(30)  NOT NULL,
    content    text         NOT NULL,
    created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_conversations_chk_1 CHECK (role IN ('user','assistant','system'))
);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_course             ON ai_conversations (course_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_course_created ON ai_conversations (user_id, course_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_memories (
    id             bigserial    PRIMARY KEY,
    user_id        bigint       NOT NULL,
    course_id      bigint,
    memory_type    varchar(50)  NOT NULL,
    memory_content text         NOT NULL,
    importance     int          NOT NULL DEFAULT 1,
    source_type    varchar(50),
    source_id      bigint,
    embedding      jsonb,
    created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_memories_chk_1 CHECK (memory_type IN ('preference','weakness','behavior_summary','risk_summary')),
    CONSTRAINT ai_memories_chk_2 CHECK (importance BETWEEN 1 AND 5),
    CONSTRAINT ai_memories_chk_3 CHECK ((source_type IS NULL) OR (source_type IN ('quiz','log','chat','agent')))
);
CREATE INDEX IF NOT EXISTS idx_ai_memories_course           ON ai_memories (course_id);
CREATE INDEX IF NOT EXISTS idx_ai_memories_user_course_type ON ai_memories (user_id, course_id, memory_type);

CREATE TABLE IF NOT EXISTS course_invites (
    id          bigserial    PRIMARY KEY,
    course_id   bigint       NOT NULL,
    invite_code varchar(50)  NOT NULL,
    max_uses    int,
    used_count  int          NOT NULL DEFAULT 0,
    expired_at  timestamp,
    status      varchar(30)  NOT NULL DEFAULT 'active',
    created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_course_invites_code UNIQUE (invite_code),
    CONSTRAINT course_invites_chk_1 CHECK (used_count >= 0),
    CONSTRAINT course_invites_chk_2 CHECK ((max_uses IS NULL) OR (max_uses >= 0)),
    CONSTRAINT course_invites_chk_3 CHECK (status IN ('active','expired','disabled'))
);
CREATE INDEX IF NOT EXISTS idx_course_invites_course ON course_invites (course_id);

CREATE TABLE IF NOT EXISTS course_members (
    id          bigserial    PRIMARY KEY,
    course_id   bigint       NOT NULL,
    user_id     bigint       NOT NULL,
    member_role varchar(30)  NOT NULL,
    joined_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status      varchar(30)  NOT NULL DEFAULT 'active',
    CONSTRAINT uk_course_members_course_user UNIQUE (course_id, user_id),
    CONSTRAINT course_members_chk_1 CHECK (member_role IN ('teacher','assistant','student')),
    CONSTRAINT course_members_chk_2 CHECK (status      IN ('active','removed'))
);
CREATE INDEX IF NOT EXISTS idx_course_members_course_id ON course_members (course_id);
CREATE INDEX IF NOT EXISTS idx_course_members_user_id   ON course_members (user_id);

CREATE TABLE IF NOT EXISTS notifications (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id       bigint       NOT NULL,
    course_id         bigint,
    notification_type varchar(50)  NOT NULL,
    title             varchar(200) NOT NULL,
    content           text         NOT NULL,
    is_read           smallint     NOT NULL DEFAULT 0,
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_chk_1 CHECK (notification_type IN ('reminder','warning','report','suggestion'))
);
CREATE INDEX IF NOT EXISTS idx_notifications_course               ON notifications (course_id);
CREATE INDEX IF NOT EXISTS idx_notifications_receiver_read_created ON notifications (receiver_id, is_read, created_at DESC);

CREATE TABLE IF NOT EXISTS weekly_reports (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id          bigint       NOT NULL,
    week_start         date         NOT NULL,
    week_end           date         NOT NULL,
    report_content     text         NOT NULL,
    weak_nodes_json    jsonb        NOT NULL,
    risk_students_json jsonb        NOT NULL,
    generated_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_weekly_reports_course_week UNIQUE (course_id, week_start),
    CONSTRAINT weekly_reports_chk_1 CHECK (week_end >= week_start)
);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_course_week ON weekly_reports (course_id, week_start DESC);

CREATE TABLE IF NOT EXISTS teaching_suggestions (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         bigint       NOT NULL,
    knowledge_node_id bigint,
    suggestion_type   varchar(50)  NOT NULL,
    title             varchar(200) NOT NULL,
    content           text         NOT NULL,
    generated_by      varchar(30)  NOT NULL DEFAULT 'agent',
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT teaching_suggestions_chk_1 CHECK (suggestion_type IN ('weak_point','resource_recommend','exercise_recommend')),
    CONSTRAINT teaching_suggestions_chk_2 CHECK (generated_by    IN ('agent','teacher'))
);
CREATE INDEX IF NOT EXISTS idx_teaching_suggestions_node        ON teaching_suggestions (knowledge_node_id);
CREATE INDEX IF NOT EXISTS idx_teaching_suggestions_course_node ON teaching_suggestions (course_id, knowledge_node_id);

-- ============================================================
-- Level 3 — depend on tables from Level 2
-- ============================================================

CREATE TABLE IF NOT EXISTS knowledge_edges (
    id             bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id      bigint        NOT NULL,
    source_node_id bigint        NOT NULL,
    target_node_id bigint        NOT NULL,
    relation_type  varchar(50)   NOT NULL,
    weight         decimal(5,2)  NOT NULL DEFAULT 1.00,
    created_at     timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_edges_relation UNIQUE (course_id, source_node_id, target_node_id, relation_type),
    CONSTRAINT knowledge_edges_chk_1 CHECK (source_node_id <> target_node_id),
    CONSTRAINT knowledge_edges_chk_2 CHECK (relation_type IN ('prerequisite','dependency','related'))
);
CREATE INDEX IF NOT EXISTS idx_knowledge_edges_course_id      ON knowledge_edges (course_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_edges_source_node_id ON knowledge_edges (source_node_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_edges_target_node_id ON knowledge_edges (target_node_id);

CREATE TABLE IF NOT EXISTS resource_knowledge (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id       bigint NOT NULL,
    knowledge_node_id bigint NOT NULL,
    CONSTRAINT uk_resource_knowledge UNIQUE (resource_id, knowledge_node_id)
);
CREATE INDEX IF NOT EXISTS idx_resource_knowledge_node ON resource_knowledge (knowledge_node_id);

CREATE TABLE IF NOT EXISTS question_options (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id    bigint      NOT NULL,
    option_label   varchar(10) NOT NULL,
    option_content text        NOT NULL,
    is_correct     smallint    NOT NULL DEFAULT 0,
    CONSTRAINT uk_question_options_label UNIQUE (question_id, option_label)
);

CREATE TABLE IF NOT EXISTS quiz_submissions (
    id           bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id      bigint        NOT NULL,
    student_id   bigint        NOT NULL,
    attempt_no   int           NOT NULL DEFAULT 1,
    submit_time  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_score  decimal(8,2)  NOT NULL DEFAULT 0.00,
    correct_rate decimal(5,2),
    status       varchar(30)   NOT NULL DEFAULT 'submitted',
    CONSTRAINT uk_quiz_submissions_attempt UNIQUE (quiz_id, student_id, attempt_no),
    CONSTRAINT quiz_submissions_chk_1 CHECK (attempt_no >= 1),
    CONSTRAINT quiz_submissions_chk_2 CHECK ((correct_rate IS NULL) OR (correct_rate BETWEEN 0 AND 100)),
    CONSTRAINT quiz_submissions_chk_3 CHECK (status IN ('submitted','graded'))
);
CREATE INDEX IF NOT EXISTS idx_quiz_submissions_quiz_id    ON quiz_submissions (quiz_id);
CREATE INDEX IF NOT EXISTS idx_quiz_submissions_student_id ON quiz_submissions (student_id);

CREATE TABLE IF NOT EXISTS quiz_questions (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id     bigint        NOT NULL,
    question_id bigint        NOT NULL,
    score       decimal(8,2)  NOT NULL DEFAULT 0.00,
    sort_order  int           NOT NULL DEFAULT 0,
    CONSTRAINT uk_quiz_questions UNIQUE (quiz_id, question_id),
    CONSTRAINT quiz_questions_chk_1 CHECK (score >= 0)
);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_question ON quiz_questions (question_id);

CREATE TABLE IF NOT EXISTS quiz_answers (
    id             bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id  bigint        NOT NULL,
    question_id    bigint        NOT NULL,
    student_answer text,
    is_correct     smallint,
    score          decimal(8,2)  NOT NULL DEFAULT 0.00,
    CONSTRAINT uk_quiz_answers_submission_question UNIQUE (submission_id, question_id),
    CONSTRAINT quiz_answers_chk_1 CHECK (score >= 0)
);
CREATE INDEX IF NOT EXISTS idx_quiz_answers_question ON quiz_answers (question_id);

CREATE TABLE IF NOT EXISTS learning_plan_tasks (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id           bigint       NOT NULL,
    knowledge_node_id bigint,
    resource_id       bigint,
    quiz_id           bigint,
    task_title        varchar(200) NOT NULL,
    task_type         varchar(50)  NOT NULL,
    due_at            timestamp,
    status            varchar(30)  NOT NULL DEFAULT 'pending',
    completed_at      timestamp,
    sort_order        int          NOT NULL DEFAULT 0,
    CONSTRAINT learning_plan_tasks_chk_1 CHECK (task_type IN ('learn_resource','finish_quiz','review_node','custom')),
    CONSTRAINT learning_plan_tasks_chk_2 CHECK (status    IN ('pending','completed','overdue','skipped'))
);
CREATE INDEX IF NOT EXISTS idx_learning_plan_tasks_plan     ON learning_plan_tasks (plan_id);
CREATE INDEX IF NOT EXISTS idx_learning_plan_tasks_node     ON learning_plan_tasks (knowledge_node_id);
CREATE INDEX IF NOT EXISTS idx_learning_plan_tasks_resource ON learning_plan_tasks (resource_id);
CREATE INDEX IF NOT EXISTS idx_learning_plan_tasks_quiz     ON learning_plan_tasks (quiz_id);

CREATE TABLE IF NOT EXISTS knowledge_mastery (
    id                bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         bigint        NOT NULL,
    student_id        bigint        NOT NULL,
    knowledge_node_id bigint        NOT NULL,
    mastery_score     decimal(5,2)  NOT NULL DEFAULT 0.00,
    mastery_level     varchar(30)   NOT NULL DEFAULT 'gray',
    last_learned_at   timestamp,
    last_quiz_score   decimal(5,2),
    risk_flag         smallint      NOT NULL DEFAULT 0,
    updated_at        timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_mastery_course_student_node UNIQUE (course_id, student_id, knowledge_node_id),
    CONSTRAINT knowledge_mastery_chk_1 CHECK (mastery_score BETWEEN 0 AND 100),
    CONSTRAINT knowledge_mastery_chk_2 CHECK (mastery_level IN ('gray','red','yellow','green')),
    CONSTRAINT knowledge_mastery_chk_3 CHECK ((last_quiz_score IS NULL) OR (last_quiz_score BETWEEN 0 AND 100))
);
CREATE INDEX IF NOT EXISTS idx_knowledge_mastery_student ON knowledge_mastery (student_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_mastery_node    ON knowledge_mastery (knowledge_node_id);

CREATE TABLE IF NOT EXISTS mastery_history (
    id                bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mastery_id        bigint        NOT NULL,
    course_id         bigint        NOT NULL,
    student_id        bigint        NOT NULL,
    knowledge_node_id bigint        NOT NULL,
    old_score         decimal(5,2),
    new_score         decimal(5,2)  NOT NULL,
    change_reason     varchar(100),
    created_at        timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mastery_history_chk_1 CHECK (new_score BETWEEN 0 AND 100)
);
CREATE INDEX IF NOT EXISTS idx_mastery_history_course          ON mastery_history (course_id);
CREATE INDEX IF NOT EXISTS idx_mastery_history_student         ON mastery_history (student_id);
CREATE INDEX IF NOT EXISTS idx_mastery_history_node            ON mastery_history (knowledge_node_id);
CREATE INDEX IF NOT EXISTS idx_mastery_history_mastery_created ON mastery_history (mastery_id, created_at DESC);

CREATE TABLE IF NOT EXISTS learning_logs (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         bigint      NOT NULL,
    student_id        bigint      NOT NULL,
    knowledge_node_id bigint,
    action_type       varchar(50) NOT NULL,
    target_id         bigint,
    duration_seconds  int,
    created_at        timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT learning_logs_chk_1 CHECK (action_type IN ('view_resource','finish_quiz','view_node','finish_task','login','chat_ai')),
    CONSTRAINT learning_logs_chk_2 CHECK ((duration_seconds IS NULL) OR (duration_seconds >= 0))
);
CREATE INDEX IF NOT EXISTS idx_learning_logs_student               ON learning_logs (student_id);
CREATE INDEX IF NOT EXISTS idx_learning_logs_course_student_created ON learning_logs (course_id, student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_learning_logs_knowledge_node_id     ON learning_logs (knowledge_node_id);

CREATE TABLE IF NOT EXISTS risk_events (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         bigint      NOT NULL,
    student_id        bigint      NOT NULL,
    knowledge_node_id bigint,
    risk_type         varchar(50) NOT NULL,
    risk_level        varchar(30) NOT NULL,
    description       text,
    status            varchar(30) NOT NULL DEFAULT 'open',
    detected_at       timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    handled_at        timestamp,
    CONSTRAINT risk_events_chk_1 CHECK (risk_type  IN ('inactive','low_quiz_score','mastery_drop','task_overdue','weak_nodes')),
    CONSTRAINT risk_events_chk_2 CHECK (risk_level IN ('low','medium','high')),
    CONSTRAINT risk_events_chk_3 CHECK (status     IN ('open','handled','ignored'))
);
CREATE INDEX IF NOT EXISTS idx_risk_events_student              ON risk_events (student_id);
CREATE INDEX IF NOT EXISTS idx_risk_events_node                 ON risk_events (knowledge_node_id);
CREATE INDEX IF NOT EXISTS idx_risk_events_course_student_status ON risk_events (course_id, student_id, status);

CREATE TABLE IF NOT EXISTS agent_jobs (
    id             bigserial    PRIMARY KEY,
    event_id       bigint,
    agent_type     varchar(50)  NOT NULL,
    course_id      bigint,
    user_id        bigint,
    job_type       varchar(50)  NOT NULL,
    status         varchar(30)  NOT NULL DEFAULT 'pending',
    input_context  jsonb        NOT NULL,
    output_summary text,
    error_message  text,
    started_at     timestamp,
    finished_at    timestamp,
    created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agent_jobs_chk_1 CHECK (agent_type IN ('learning_plan','course_operation','analysis','teaching_suggestion')),
    CONSTRAINT agent_jobs_chk_2 CHECK (job_type   IN ('heartbeat','event_trigger','manual')),
    CONSTRAINT agent_jobs_chk_3 CHECK (status     IN ('pending','running','success','failed'))
);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_event               ON agent_jobs (event_id);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_course              ON agent_jobs (course_id);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_user                ON agent_jobs (user_id);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_type_status_created ON agent_jobs (agent_type, status, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_outputs (
    id             bigserial    PRIMARY KEY,
    agent_job_id   bigint       NOT NULL,
    course_id      bigint,
    user_id        bigint,
    output_type    varchar(50)  NOT NULL,
    content        text         NOT NULL,
    model_name     varchar(100),
    prompt_version varchar(100),
    created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agent_outputs_chk_1 CHECK (output_type IN ('learning_plan','warning','teaching_suggestion','weekly_report'))
);
CREATE INDEX IF NOT EXISTS idx_agent_outputs_job    ON agent_outputs (agent_job_id);
CREATE INDEX IF NOT EXISTS idx_agent_outputs_course ON agent_outputs (course_id);
CREATE INDEX IF NOT EXISTS idx_agent_outputs_user   ON agent_outputs (user_id);


CREATE TABLE IF NOT EXISTS student_memory (
    id BIGSERIAL PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id  BIGINT NOT NULL,
    memory_json TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, course_id)
);
-- ============================================================
-- Seed data
-- ============================================================
INSERT INTO roles (id, role_code, role_name) VALUES (1, 'teacher', 'Teacher') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, role_code, role_name) VALUES (2, 'student', 'Student') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, role_code, role_name) VALUES (3, 'admin', 'Admin') ON CONFLICT DO NOTHING;
SELECT setval('roles_id_seq', 3, true);
